platform :ios, '10.0'

def shared_pods
  pod 'SwrveSDKCommon', :path => '../..'
  pod 'SwrveConversationSDK', :path => '../..'
  pod 'SwrveSDK', :path => '../..'
  # use remote podfile by commenting out above and uncommenting below
  #pod 'SwrveSDK'
end

target 'RichPushSample-ObjC' do
  shared_pods
end

target 'RichPushSampleServiceExtension-ObjC' do
  pod 'SwrveSDKCommon', :path => '../..'

  #use remote podfile by commenting out above and uncommenting below
  #pod 'SwrveSDKCommon', '6.1.2'
end


target 'RichPushSample-Swift' do
  use_frameworks!
  shared_pods
end

target 'RichPushSampleServiceExtension-Swift' do
  use_frameworks!
  pod 'SwrveSDKCommon', :path => '../..'
  #use remote podfile by commenting out above and uncommenting below
  #pod 'SwrveSDKCommon', '6.1.1'
end
