platform :ios, '10.0'

def shared_pods
  pod 'SwrveSDK', :path => '../../'
  pod 'SwrveSDKCommon', :path => '../../'
  # use remote podfile by commenting out above and uncommenting below
  #pod 'SwrveSDK'
end

target 'RichPushSample-ObjC' do
  use_frameworks!
  shared_pods
end

target 'RichPushSampleServiceExtension-ObjC' do
  use_frameworks!
  pod 'SwrveSDKCommon', :path => '../../'

  #use remote podfile by commenting out above and uncommenting below
  #pod 'SwrveSDKCommon'
end


target 'RichPushSample-Swift' do
  use_frameworks!
  shared_pods
end

target 'RichPushSampleServiceExtension-Swift' do
  use_frameworks!
  pod 'SwrveSDKCommon', :path => '../../'
  #use remote podfile by commenting out above and uncommenting below
  #pod 'SwrveSDKCommon'
end
