platform :ios, '14.0'

def shared_pods
  pod 'SwrveSDK', :path => '../../'
  pod 'SwrveSDKCommon', :path => '../../'
  # use remote podfile by commenting out above and uncommenting below
  #pod 'SwrveSDK'
end

target 'RichPushSample' do
  use_frameworks!
  shared_pods
end

target 'RichPushSampleServiceExtension' do
  use_frameworks!
  pod 'SwrveSDKCommon', :path => '../../'
  #use remote podfile by commenting out above and uncommenting below
  #pod 'SwrveSDKCommon'
end
