platform :ios, '8.0'

def shared_pods
  pod 'SwrveSDK'
end

target 'MinimalIntegrationSample-ObjC' do
  shared_pods
end

target 'MinimalIntegrationSample-Swift' do
  use_frameworks!
  shared_pods
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '8.0'
          config.build_settings['CLANG_WARN_DOCUMENTATION_COMMENTS'] = 'NO'
      end
  end
end