version: 2.1

jobs:
  build:
    macos:
      xcode: 26.3.0
    resource_class: m4pro.medium
    steps:
      - checkout
      - run:
          name: pod install
          command: |
            cd SwrveSDKTest
            pod install
      - run: fastlane unitTestsiOS scheme:"SwrveSDKiOS" device:"iPhone 17 (26.3)"
      - run: fastlane unitTeststvOS scheme:"SwrveSDKtvOS"
      - store_test_results:
          path: fastlane/test_output/

workflows:
  build_and_test:
    jobs:
      - build
