target 'SwrveSDKTest' do
  pod 'OCMock', '~> 3.4.1'
  pod 'SwrveSDKCommon', :path => '../'
  pod 'SwrveConversationSDK', :path => '../'
  pod 'SwrveSDK', :path => '../'
  #pod 'SwrveSDK', '~> 5.2.1'
end

target 'SwrveSDKTestTests' do
  pod 'OCMock', '~> 3.4.1'
  pod 'SwrveSDKCommon', :path => '../'
  pod 'SwrveConversationSDK', :path => '../'
  pod 'SwrveSDK', :path => '../'
  #pod 'SwrveSDK', '~> 5.2.1'
end
