platform :ios, '10.0'

target 'SwrveSDKTest' do
  pod 'SwrveSDKCommon', :path => '../'
  pod 'SwrveConversationSDK', :path => '../'
  pod 'SwrveSDK', :path => '../'
  #pod 'SwrveSDK', '~> 5.3.3'

  target 'SwrveSDKTestTests' do
    pod 'OCMock', '~> 3.4.1'
    inherit! :search_paths
  end
end

post_install do |installer_representation|
   installer_representation.pods_project.targets.each do |target|
       target.build_configurations.each do |config|
           config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] = ['$(inherited)', 'SWRVE_LOG_IDFA', 'SWRVE_LOG_IDFV']

           # Need to specify the deployment version xcodebuild otherwise causes warnings
           config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = "10.0"
       end
   end
end
