install! 'cocoapods', :generate_multiple_pod_projects => true, :incremental_installation => true
platform :ios, '10.0'

def shared_pods
  pod 'SwrveSDK', :path => '../../'
  pod 'SwrveSDKCommon', :path => '../../'
  # use remote podfile by commenting out above and uncommenting below
  #pod 'SwrveSDK'
end

target 'CustomUserId-ObjC' do
  use_frameworks!
  shared_pods
end

target 'CustomUserId-Swift' do
  use_frameworks!
  shared_pods
end

post_install do |installer|
  unless installer.pods_project.nil?
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '10.0'
        config.build_settings['CLANG_WARN_DOCUMENTATION_COMMENTS'] = 'NO'
      end
    end
  end
end
