use_frameworks!

target 'RichPushSample' do
  pod 'SwrveSDKCommon', :path => '../../..'
  pod 'SwrveConversationSDK', :path => '../../..'
  pod 'SwrveSDK', :path => '../../..'

  # use remote podfile by commenting out above and uncommenting below
  #pod 'SwrveSDK', '4.11'
end

target 'RichPushSampleServiceExtension' do
  pod 'SwrveSDKCommon', :path => '../../..'
  
  #use remote podfile by commenting out above and uncommenting below
  #pod 'SwrveSDKCommon', '4.11'
end
