platform :ios, '16.0'

target 'SwrveEmbeddedSample' do
  use_frameworks!

  # Pods for SwrveEmbeddedSample
  pod 'SwrveSDK'
# To build against local SDK source instead, comment out the line above and uncomment these two:
#  pod 'SwrveSDK', :path => '../../'
#  pod 'SwrveSDKCommon', :path => '../../'

end
