platform :ios, '16.0'

target 'SwrveEmbeddedSample' do
  use_frameworks!

  # Pods for SwrveEmbeddedSample
  pod 'SwrveSDK'
# To use local pods, uncomment below
#  pod 'SwrveSDK', :path => '../../'
#  pod 'SwrveSDKCommon', :path => '../../'

end
