use_frameworks!

target 'MessageCenterSample' do
  pod 'SwrveSDKCommon', :path => '../../..'
  pod 'SwrveConversationSDK', :path => '../../..'
  pod 'SwrveSDK', :path => '../../..'

  # use remote podfile by commenting out above and uncommenting below
  #pod 'SwrveSDK', '5.1.0'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '8.0'
            config.build_settings['CLANG_WARN_DOCUMENTATION_COMMENTS'] = 'NO'
        end
    end
end
