use_frameworks!

target 'MessageCenterSample' do
  pod 'SwrveSDK', '4.5.2'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '7.0'
        end
    end
end