# Customize this file, documentation can be found here:
# https://docs.fastlane.tools/actions/
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.65.0"

default_platform :ios

platform :ios do
  before_all do
    setup_circle_ci
  end

  desc "Run iOS Tests"
  lane :unitTestsiOS do |options|
    scan(
      workspace: "SwrveSDKTest/SwrveSDKTest.xcworkspace",
      scheme: options[:scheme],
      device: options[:device],
      devices: options[:devices],
      code_coverage: options[:coverage],
      output_directory: options[:output_directory],
      build_for_testing: options[:build_for_testing],
      test_without_building: options[:test_without_building],
      derived_data_path: options[:derived_data_path]
    )
  end
  
  desc "Run tvOS tests"
  lane :unitTeststvOS do |options|
    scan(
      workspace: "SwrveSDKTest/SwrveSDKTest.xcworkspace",
      scheme: options[:scheme],
      device: options[:device],
      code_coverage: options[:coverage],
      output_directory: options[:output_directory],
      derived_data_path: options[:derived_data_path]
    )
  end

end

# More information about multiple platforms in fastlane: https://docs.fastlane.tools/advanced/#control-configuration-by-lane-and-by-platform
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used. No personal data is recorded.
# Learn more at https://docs.fastlane.tools/#metrics
