import XCTest

class SwrveTestLocalStorage: XCTestCase {

    override func setUp() {
        super.setUp()
        SwrveTestHelper.setUp()
    }

    override func tearDown() {
        super.tearDown()
        SwrveTestHelper.tearDown()
    }

    func testApplicationSupportCreatesNewFile() {
        let fileManager = FileManager.default
        if let appSupportDir = SwrveLocalStorage.applicationSupportPath() {
            XCTAssertTrue(fileManager.fileExists(atPath: appSupportDir), "File is not generated by Application Support")
        } else {
            XCTFail("testApplicationSupportCreatesNewFile: Application Support path is nil")
        }
    }

    func testApplicationSupportDoesntOverride() {
        let path = [SwrveLocalStorage.applicationSupportPath(), "testFile"].joined(separator: "/")
        try? "[]".write(toFile: path, atomically: true, encoding: .utf8)

        // Call path again, and then check if the written file is still present and unaltered
        let path2 = [SwrveLocalStorage.applicationSupportPath(), "testFile"].joined(separator: "/")
        let content = try? String(contentsOfFile: path2, encoding: .utf8)

        XCTAssertEqual(content, "[]", "testApplicationSupportDoesntOverride: \(String(describing: content)) does not equal '[]'")
    }

    func testFlushFrequencyKey() {
        SwrveLocalStorage.saveFlushFrequency(999)
        let result = SwrveLocalStorage.flushFrequency()
        let expected = UserDefaults.standard.double(forKey: "swrve_cr_flush_frequency")
        XCTAssertTrue(result == expected)

        // Remove from defaults
        UserDefaults.standard.removeObject(forKey: "swrve_cr_flush_frequency")
        let resultAfterRemoval = UserDefaults.standard.double(forKey: "swrve_cr_flush_frequency")
        XCTAssertTrue(resultAfterRemoval == 0)

        // It will still be in backup store
        let resultFromBackup = SwrveLocalStorage.flushFrequency()
        XCTAssertTrue(resultFromBackup == 999)
    }

    func testFlushDelayKey() {
        SwrveLocalStorage.saveflushDelay(999)
        let result = SwrveLocalStorage.flushDelay()
        let expected = UserDefaults.standard.double(forKey: "swrve_cr_flush_delay")
        XCTAssertTrue(result == expected)

        // Remove from defaults
        UserDefaults.standard.removeObject(forKey: "swrve_cr_flush_delay")
        let resultAfterRemoval = UserDefaults.standard.double(forKey: "swrve_cr_flush_delay")
        XCTAssertTrue(resultAfterRemoval == 0)

        // It will still be in backup store
        let resultFromBackup = SwrveLocalStorage.flushDelay()
        XCTAssertTrue(resultFromBackup == 999)
    }

    func testETagKey() {
        SwrveLocalStorage.saveETag("SomeETag", forUserId: "TestUser")
        let result = SwrveLocalStorage.eTag(forUserId: "TestUser")
        let expected = UserDefaults.standard.string(forKey: "TestUsercampaigns_and_resources_etag")
        XCTAssertTrue(result == expected)

        // Remove from defaults
        UserDefaults.standard.removeObject(forKey: "TestUsercampaigns_and_resources_etag")
        let resultAfterRemoval = UserDefaults.standard.string(forKey: "TestUsercampaigns_and_resources_etag")
        XCTAssertNil(resultAfterRemoval)

        // It will still be in backup store
        let resultFromBackup = SwrveLocalStorage.eTag(forUserId: "TestUser")
        XCTAssertTrue(resultFromBackup == "SomeETag")
    }

    func testDeviceTokenKey() {
        SwrveLocalStorage.saveDeviceToken("SomeDeviceToken")
        let result = SwrveLocalStorage.deviceToken()
        let expected = UserDefaults.standard.string(forKey: "swrve_device_token") as? String
        XCTAssertTrue(result as? String == expected)

        // Remove from defaults
        UserDefaults.standard.removeObject(forKey: "swrve_device_token")
        let resultAfterRemoval = UserDefaults.standard.string(forKey: "swrve_device_token")
        XCTAssertNil(resultAfterRemoval)

        // It will still be in backup store
        let resultFromBackup = SwrveLocalStorage.deviceToken() as? String
        XCTAssertTrue(resultFromBackup == "SomeDeviceToken")
    }

    func testDeviceUUIDKey() {
        let udid = UUID().uuidString
        SwrveLocalStorage.saveDeviceUUID(udid)
        let result = SwrveLocalStorage.deviceUUID()
        let expected = UserDefaults.standard.object(forKey: "swrve_device_uuid") as? String
        XCTAssertTrue(result == expected)

        // Remove from defaults
        UserDefaults.standard.removeObject(forKey: "swrve_device_uuid")
        let resultAfterRemoval = UserDefaults.standard.string(forKey: "swrve_device_uuid")
        XCTAssertNil(resultAfterRemoval)

        // It will still be in backup store
        let resultFromBackup = SwrveLocalStorage.deviceUUID()
        XCTAssertTrue(resultFromBackup == udid)
    }

    func testSwrveUserIDKey() {
        SwrveLocalStorage.saveSwrveUserId("SomeUserID")
        let result = SwrveLocalStorage.swrveUserId()
        let expected = UserDefaults.standard.object(forKey: "swrve_user_id") as? String
        XCTAssertTrue(result == expected)

        // Remove from defaults
        UserDefaults.standard.removeObject(forKey: "SomeUserID")
        let resultAfterRemoval = UserDefaults.standard.string(forKey: "SomeUserID")
        XCTAssertNil(resultAfterRemoval)

        // It will still be in backup store
        let resultFromBackup = SwrveLocalStorage.swrveUserId()
        XCTAssertTrue(resultFromBackup == "SomeUserID")
    }

    func testSwrveTrackingStateKey() {
        var trackingStateUnknown = SwrveLocalStorage.trackingState()
        XCTAssertEqual(swiftTrackingState(from: trackingStateUnknown), .UNKNOWN)  // UNKNOWN to start with

        SwrveLocalStorage.saveTrackingState(EVENT_SENDING_PAUSED)
        var trackingStatePaused = SwrveLocalStorage.trackingState()
        XCTAssertEqual(swiftTrackingState(from: trackingStatePaused), .EVENT_SENDING_PAUSED)

        if let expectedNumber = UserDefaults.standard.object(forKey: "swrve_tracking_state") as? NSNumber {
            //            XCTAssertEqual(expectedNumber.intValue, trackingStatePaused.rawValue)
            XCTAssertEqual(UInt32(expectedNumber.intValue), trackingStatePaused.rawValue)
        } else {
            XCTFail("swrve_tracking_state not found in UserDefaults")
        }
    }

    func testPermissionsKey() {
        SwrveLocalStorage.savePermissions(["SomeKey": "SomeValue"])
        if let expected = UserDefaults.standard.dictionary(forKey: "swrve_permission_status") as? [String: String] {
            XCTAssertEqual(expected["SomeKey"], "SomeValue")
        } else {
            XCTFail("No permissions found in UserDefaults.")
        }

        // Remove from defaults
        UserDefaults.standard.removeObject(forKey: "swrve_permission_status")
        let expectedDicAfterRemoval = UserDefaults.standard.dictionary(forKey: "swrve_permission_status")
        XCTAssertNil(expectedDicAfterRemoval)

        // It will still be in backup store
        let expectedDicFromBackup = SwrveLocalStorage.getPermissions() as? [String: String]
        XCTAssertEqual(expectedDicFromBackup, ["SomeKey": "SomeValue"])
    }

    func testAskForPermissionsKey() {
        SwrveLocalStorage.saveAsked(forPushPermission: true)
        let result = SwrveLocalStorage.askedForPushPermission()
        let expected = UserDefaults.standard.bool(forKey: "swrve.asked_for_push_permission")
        XCTAssertEqual(result, expected)

        // Remove from defaults
        UserDefaults.standard.removeObject(forKey: "swrve.asked_for_push_permissions")
        let expectedAfterRemoval = UserDefaults.standard.bool(forKey: "swrve.asked_for_push_permissions")
        XCTAssertFalse(expectedAfterRemoval)

        // It will still be in backup store
        let expectedFromBackup = SwrveLocalStorage.askedForPushPermission()
        XCTAssertTrue(expectedFromBackup)
    }

    func testSaveSwrveUsers() {
        guard let user1 = SwrveUser(externalId: "TestEx1", swrveId: "TestSw1", verified: true),
            let user2 = SwrveUser(externalId: "TestEx2", swrveId: "TestSw2", verified: false)
        else {
            XCTFail("Failed to create SwrveUser instances")
            return
        }
        let mArray: [SwrveUser] = [user1, user2]

        guard let data = try? NSKeyedArchiver.archivedData(withRootObject: mArray, requiringSecureCoding: false) else {
            XCTFail("Failed to archive SwrveUser array")
            return
        }
        SwrveLocalStorage.saveSwrveUsers(data)

        let swrveUsers = SwrveLocalStorage.swrveUsers()
        if let expected = UserDefaults.standard.object(forKey: "swrve_users") as? Data {
            XCTAssertEqual(swrveUsers, expected)

            // Check contents of expected data
            if let unarchivedUsers = try? NSKeyedUnarchiver.unarchiveTopLevelObjectWithData(expected) as? [SwrveUser] {
                // Assert the number of users
                XCTAssertEqual(unarchivedUsers.count, 2)

                // Assert properties of each user (optional)
                //                XCTAssertEqual(unarchivedUsers[0].externalId, "TestEx1")
                //                XCTAssertEqual(unarchivedUsers[1].externalId, "TestEx2")
            } else {
                XCTFail("Failed to unarchive users from UserDefaults")
            }
        } else {
            XCTFail("No users found in UserDefaults.")
        }

        // Remove from defaults
        UserDefaults.standard.removeObject(forKey: "swrve_users")
        let expectedAfterRemoval = UserDefaults.standard.object(forKey: "swrve_users") as? Data
        XCTAssertNil(expectedAfterRemoval)

        // It will still be in backup store
        let expectedFromBackup = swrveUsers
        XCTAssertEqual(expectedFromBackup, data)
    }

    enum SwrveTrackingStateSwift: Int {
        case UNKNOWN = 0
        case STARTED = 1
        case EVENT_SENDING_PAUSED = 2
        case STOPPED = 3
    }

    private func swiftTrackingState(from objcState: SwrveTrackingState) -> SwrveTrackingStateSwift {
        switch objcState.rawValue {
        case 0: return .UNKNOWN
        case 1: return .STARTED
        case 2: return .EVENT_SENDING_PAUSED
        case 3: return .STOPPED
        default: return .UNKNOWN
        }
    }
}
