target 'SwrveStandalonesTest' do
  pod 'SwrveCommon', :path => '../SwrveCommon'
  pod 'SwrveLocationSDK', :path => '../SwrveLocationSDK'
  pod 'SwrveConversationSDK', :path => '../SwrveConversationSDK'
end

