target 'SwrveStandalonesTest' do
  pod 'SwrveSDKCommon', :path => '../SwrveSDKCommon'
  pod 'SwrveLocationSDK', :path => '../SwrveLocationSDK'
  pod 'SwrveConversationSDK', :path => '../SwrveConversationSDK'
  pod 'SwrveSDK', :path => '../'
end

