
target 'SwrveDemoFramework' do
    pod 'SwrveSDKCommon', :path => '../'
    pod 'SwrveConversationSDK', :path => '../'
    pod 'SwrveSDK', :path => '../'

    #comment out above and uncomment below to switch to remote CocoaPods
    #pod 'SwrveSDK', '~> 4.8.0'
end
