target 'ChangeUserID' do
  pod 'SwrveSDKCommon', :path => '../../..'
  pod 'SwrveConversationSDK', :path => '../../..'
  pod 'SwrveSDK', :path => '../../..'

  # use remote podfile by commenting out above and uncommenting below
  #pod 'SwrveSDK', '4.8.0'
end
