target 'MessageCenterSample' do
  pod 'SwrveSDKCommon', :path => '../../SwrveSDKCommon'
  pod 'SwrveConversationSDK', :path => '../../SwrveConversationSDK'
  pod 'SwrveSDK', :path => '../../SwrveSDK'
end
